import {defineConfig} from "@anio-software/enkore"
import {defineTargetOptions} from "@anio-software/enkore.target-js-node"
import {
	generateFactoryWithInstantiationFile
} from "@anio-software/enkore.target-js-node/autogenerate"

export const config: unknown = defineConfig({
	target: {
		name: "js-node",
		options: defineTargetOptions({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: [
		...generateFactoryWithInstantiationFile({
			source: "project/src/__findNearestFileXXX.as.ts",
			destination: "project/export/__findNearestFileXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__hashFileXXX.as.ts",
			destination: "project/export/__hashFileXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__openFileXXX.as.ts",
			destination: "project/export/__openFileXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__readFileInChunksXXX.as.ts",
			destination: "project/export/__readFileInChunksXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__readFileJSONXXX.as.ts",
			destination: "project/export/__readFileJSONXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__readFileStringXXX.as.ts",
			destination: "project/export/__readFileStringXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__writeAtomicFileJSONXXX.as.ts",
			destination: "project/export/__writeAtomicFileJSONXXXFactory.as.ts"
		}),
		...generateFactoryWithInstantiationFile({
			source: "project/src/__writeAtomicFileXXX.as.ts",
			destination: "project/export/__writeAtomicFileXXXFactory.as.ts"
		})
	]
})
